FROM opensuse/leap:42

RUN zypper addrepo -c --no-gpgcheck https://oss.atix.de/SLES12SP5/ subscription-manager
RUN zypper removerepo 'OSS Update'
RUN zypper clean --all
RUN zypper install -y make python-pip subscription-manager zypp-plugin-python which python-setuptools python-virtualenv lsof

WORKDIR /app
