FROM quay.io/centos/centos:stream9

RUN dnf install -y https://yum.theforeman.org/client/nightly/el9/x86_64/foreman-client-release.rpm && dnf clean all
RUN dnf install make python3 python3-pip python3-dnf-plugins-core subscription-manager -y && dnf clean all
WORKDIR /app
