FROM quay.io/centos/centos:stream8

RUN dnf install -y https://yum.theforeman.org/client/nightly/el8/x86_64/foreman-client-release.rpm && dnf clean all
RUN dnf install make python3-gofer python3-dnf-plugins-core python3-tracer python3-gofer-proton subscription-manager -y && dnf clean all
WORKDIR /app
