FROM debian:11

RUN apt-get update && apt-get install --yes --no-install-recommends curl make python3 python3-pip python3-setuptools && apt-get clean
RUN curl -o /etc/apt/trusted.gpg.d/atix.asc https://oss.atix.de/atix_gpg.pub
RUN echo 'deb https://oss.atix.de/Debian11/ stable main' >> /etc/apt/sources.list
RUN apt-get update && apt-get install --yes --no-install-recommends python3-subscription-manager && apt-get clean

WORKDIR /app
